/* =========================================================
 * topic-catalog.js — 专题目录唯一数据源
 * index.html（精选 feat:true）与 explore-map.html（全量）共用，
 * 替代原先两页各自手写的重复 HTML 列表。
 * 字段：id(topic.html?p=) / title / loc / desc / ch(印章字) /
 *       img(art/ 下封面 svg 文件名) / ring(印章描边色) / feat(首页精选)
 * ========================================================= */
window.TOPIC_CATALOG = [
  { id: 'cz',  ch: '征', img: 'topic-changzheng', ring: 'var(--color-primary)',     feat: true,
    title: '红军长征路线地图', loc: '江西 · 贵州 · 四川 · 甘肃 · 陕西',
    desc: '战役、会议与纪念地，四条行军路线，一段走得最远的路。' },
  { id: 'gy',  ch: '滇', img: 'topic-yunnan', ring: 'var(--color-green)',           feat: true,
    title: '广西云南山水地图', loc: '桂林 · 阳朔 · 大理 · 西双版纳',
    desc: '山水与烟火之间，七条推荐路线，慢慢走。' },
  { id: 'qt',  ch: '藏', img: 'topic-tibet', ring: 'var(--color-primary-dark)',     feat: true,
    title: '青藏风光地图', loc: '唐蕃古道 · 山南 · 阿里 · 新藏线',
    desc: '进藏路线与人文地理，越往西走，天地越开阔。' },
  { id: 'sx',  ch: '晋', img: 'topic-shanxi', ring: 'var(--color-blue)',            feat: true,
    title: '山西古建地图', loc: '大同 · 太原 · 平遥 · 运城',
    desc: '国保古建，四条探访路线，梁柱之间是一千年的风雨。' },
  { id: 'sc',  ch: '川', img: 'topic-sc', ring: 'var(--color-primary)',             feat: true,
    title: '四川风光人文地图', loc: '成都 · 九寨沟 · 稻城亚丁 · 峨眉山',
    desc: '天府之国，四百余处山水古迹与蜀味，十条推荐路线。' },
  { id: 'gs',  ch: '陇', img: 'topic-gs', ring: '#C9A05C',                          feat: true,
    title: '甘肃丝路人文地图', loc: '敦煌 · 嘉峪关 · 张掖 · 甘南 · 天水',
    desc: '河西走廊三百余处丝路佛光、丹霞草原与陇味，九条推荐路线。' },
  { id: 'xj',  ch: '疆', img: 'topic-xj', ring: '#3E7CB1',                          feat: true,
    title: '新疆丝路风光地图', loc: '喀纳斯 · 伊犁 · 喀什 · 独库公路 · 吐鲁番',
    desc: '大美西域近两百处雪山草原、丝路古城与疆味，九条推荐路线。' },
  { id: 'gz',  ch: '黔', img: 'topic-gz', ring: 'var(--color-green)',               feat: true,
    title: '贵州山水人文地图', loc: '黄果树 · 荔波 · 西江 · 梵净山 · 镇远',
    desc: '多彩黔境一百六十余处瀑布溶洞、苗乡侗寨与黔味，九条推荐路线。' },
  { id: 'qh',  ch: '青', img: 'topic-qh', ring: '#3E7CB1',
    title: '青海大美山河地图', loc: '青海湖 · 茶卡 · 翡翠湖 · 水上雅丹 · 可可西里',
    desc: '四十六处盐湖雪山、草原江河与青味，三条大西北经典线。' },
  { id: 'xz',  ch: '藏', img: 'topic-xz', ring: '#9C9A92',
    title: '西藏圣境之旅地图', loc: '布达拉宫 · 林芝 · 珠峰 · 阿里 · 然乌湖',
    desc: '二百余处神山圣湖、藏寺秘境与藏味，圣城/林芝/阿里三条线。' },
  { id: 'nmg', ch: '蒙', img: 'topic-nmg', ring: '#5F8A6B',
    title: '内蒙古草原风情地图', loc: '呼伦贝尔 · 额济纳 · 响沙湾 · 阿尔山 · 满洲里',
    desc: '三十四处草原沙漠、森林边境与蒙味，草原/胡杨/阿尔山三条线。' },
  { id: 'sx2', ch: '秦', img: 'topic-sx2', ring: '#A9563B',
    title: '陕西三秦人文地图', loc: '兵马俑 · 华山 · 壶口 · 延安 · 大唐不夜城',
    desc: '三十一处古迹名城、峡谷丹霞与秦味，古都/陕北/秦岭三条线。' },
  { id: 'cq',  ch: '渝', img: 'topic-cq', ring: '#8A5A44',
    title: '重庆魔幻山水地图', loc: '洪崖洞 · 武隆 · 大足 · 三峡 · 磁器口',
    desc: '二十七处魔幻地标、喀斯特奇观与渝味，都市/武隆/三峡三条线。' },
  { id: 'nx',  ch: '宁', img: 'topic-nx', ring: '#C9A05C',
    title: '宁夏塞上江南地图', loc: '沙坡头 · 西夏王陵 · 镇北堡 · 贺兰山岩画',
    desc: '十七处大漠黄河、古迹石窟与宁味，银川/沙坡头/固原三条线。' },
  { id: 'bj',  ch: '京', img: 'topic-bj', ring: 'var(--color-ink-soft)',
    title: '北京古都人文地图', loc: '故宫 · 长城 · 胡同',
    desc: '六百年帝都，红墙金瓦与胡同烟火。' },
  { id: 'tj',  ch: '津', img: 'topic-tj', ring: 'var(--color-ink-soft)',
    title: '天津海河人文地图', loc: '海河 · 五大道 · 盘山',
    desc: '九河下梢，洋楼与海河灯火。' },
  { id: 'sd',  ch: '鲁', img: 'topic-sd', ring: 'var(--color-ink-soft)',
    title: '山东齐鲁山海地图', loc: '泰山 · 三孔 · 崂山',
    desc: '一山一水一圣人，齐鲁风华。' },
  { id: 'ln',  ch: '辽', img: 'topic-ln', ring: 'var(--color-ink-soft)',
    title: '辽宁山海关东地图', loc: '沈阳故宫 · 大连海滨 · 本溪水洞',
    desc: '山海关东，共和国的长子。' },
  { id: 'jl',  ch: '吉', img: 'topic-jl', ring: 'var(--color-ink-soft)',
    title: '吉林长白神韵地图', loc: '长白山 · 雾凇 · 查干湖',
    desc: '长白神山，一山有四季。' },
  { id: 'hlj', ch: '黑', img: 'topic-hlj', ring: 'var(--color-ink-soft)',
    title: '黑龙江北国风光地图', loc: '哈尔滨 · 雪乡 · 北极村',
    desc: '北国风光，千里冰封。' },
  { id: 'he',  ch: '冀', img: 'topic-he', ring: 'var(--color-ink-soft)',
    title: '河北燕赵大地地图', loc: '北戴河 · 避暑山庄 · 草原天路',
    desc: '燕赵慷慨，山海与坝上风光。' },
  { id: 'ha',  ch: '豫', img: 'topic-ha', ring: 'var(--color-ink-soft)',
    title: '河南中原大地地图', loc: '少林 · 龙门 · 云台山',
    desc: '中原大地，一部河南史半部中国史。' },
  { id: 'sh',  ch: '沪', img: 'topic-sh', ring: 'var(--color-ink-soft)',
    title: '上海海派都会地图', loc: '外滩 · 迪士尼 · 豫园',
    desc: '东方明珠下的都会魅力。' },
  { id: 'js',  ch: '苏', img: 'topic-js', ring: 'var(--color-ink-soft)',
    title: '江苏水韵江南地图', loc: '园林 · 秦淮 · 瘦西湖',
    desc: '水韵江南，园林甲天下。' },
  { id: 'zj',  ch: '浙', img: 'topic-zj', ring: 'var(--color-ink-soft)',
    title: '浙江诗画山水地图', loc: '西湖 · 普陀 · 乌镇',
    desc: '诗画江南，山水浙江。' },
  { id: 'ah',  ch: '皖', img: 'topic-ah', ring: 'var(--color-ink-soft)',
    title: '安徽徽韵山水地图', loc: '黄山 · 宏村 · 九华',
    desc: '徽风皖韵，天下黄山。' },
  { id: 'fj',  ch: '闽', img: 'topic-fj', ring: 'var(--color-ink-soft)',
    title: '福建山海福地地图', loc: '鼓浪屿 · 武夷山 · 土楼',
    desc: '山海画廊，八闽福地。' },
  { id: 'jx',  ch: '赣', img: 'topic-jx', ring: 'var(--color-ink-soft)',
    title: '江西红色赣鄱地图', loc: '庐山 · 婺源 · 井冈山',
    desc: '红色圣地，绿色家园。' },
  { id: 'gd',  ch: '粤', img: 'topic-gd', ring: 'var(--color-ink-soft)',
    title: '广东岭南风情地图', loc: '广州塔 · 丹霞山 · 长隆',
    desc: '岭南烟火，湾区魅力。' },
  { id: 'hi',  ch: '琼', img: 'topic-hi', ring: 'var(--color-ink-soft)',
    title: '海南热带海岛地图', loc: '三亚 · 蜈支洲 · 五指山',
    desc: '热带天堂，阳光海岛。' },
  { id: 'hk',  ch: '港', img: 'topic-hk', ring: '#3E7CB1',
    title: '香港都会山海地图', loc: '维港 · 太平山顶 · 迪士尼 · 南丫岛',
    desc: '都会与山海之间，维港灯火与离岛风光。' },
  { id: 'mo',  ch: '澳', img: 'topic-mo', ring: '#B4785A',
    title: '澳门中西风情地图', loc: '大三巴 · 旅游塔 · 官也街 · 路氹',
    desc: '中西交融四百年，牌坊老街与度假村灯火。' },
  { id: 'tw',  ch: '台', img: 'topic-tw', ring: '#C9A05C',
    title: '台湾宝岛山海地图', loc: '台北101 · 日月潭 · 太鲁阁 · 垦丁',
    desc: '宝岛山海，夜市老街的烟火日常。' },
  { id: 'nation', ch: '国', img: '', ring: '', nation: true,
    title: '全国景点地图', loc: '36 专题 · 7833 处 · 34 省 · 561 道风味 · 13 条路线',
    desc: '地图 / 列表 / 主题 / 路线 / 美食 · 点击地图查附近 · 分省筛选 · 模糊搜索' }
];
